export const resumeData = {
  name: "Kevin He",
  contact: {
    email: "contact@kevinh.dev",
    phone: "+64-451-781-138",
    website: "kevinh.dev",
    github: "kevinh-e",
  },
  education: [
    {
      institution: "University of New South Wales",
      location: "Sydney, NSW",
      degree: "BA in Computer Science",
      period: "Feb. 2023 – Oct. 2026",
    },
    {
      institution: "Normanhurst Boys High School",
      location: "Sydney, NSW",
      degree: "Higher School Certificate",
      period: "Feb. 2017 – Nov. 2022",
    },
  ],
  technologies: {
    Languages: [
      "Python",
      "Java",
      "JavaScript/TypeScript",
      "C",
      "SQL (Postgres)",
      "Bash",
      "Lua",
    ],
    "Frameworks and Libraries": [
      "React",
      "Next.js",
      "Node.js",
      "PyTorch",
      "TailwindCSS",
      "TanStack",
      "MongoDB",
    ],
    "Developer Tools": [
      "Git",
      "Docker",
      "Linux",
      "NeoVim",
      "Markdown",
      "Figma",
      "Vercel",
      "Copilot",
    ],
  },
  projects: [
    {
      name: "Deep NN Chess Engine",
      technologies: ["PyTorch", "Tensorboard", "Google Colab"],
      year: "2025",
      details: [
        "Designed a neural network–based chess engine using self-play and MCTS inspired by AlphaZero",
        "Accelerated training by leveraging multiprocessing, batched inference, mixed precision, and layer pruning to save training time by 1700% versus a naive single-CPU loop",
        "Streamlined a self-play data generation pipeline alongside supervised learning in Python to bootstrap engine performance to ≈ 2000 ELO within only 10 hours",
        "Achieved a competitive ELO on custom test suites against Stockfish-level tactics while training cost was free",
      ],
      link: "https://github.com/kevinh-e/deep-nn-chess-engine",
      linkType: "Github",
    },
    {
      name: "TasteBuds",
      technologies: [
        "Next.js",
        "React",
        "Socket.io",
        "Node.js",
        "TailwindCSS",
        "Git",
        "Shadcn/UI",
      ],
      year: "2025",
      isBig: true,
      details: [
        "Developed a gamified cuisine recommendation application with real-time multi-user interaction via Socket.io",
        "Leveraged Shadcn/UI and other component libraries to design a modern, responsive frontend",
        "Optimised developer workflows and productivity using GitHub to deploy a working MVP within 3 days",
        "Led a 4-person development team to a 2nd‑place finish at the 2025 DevSoc Hackabyte Hackathon",
      ],
      link: "https://tastebuds.kevinh.dev",
      linkType: "Live Site",
    },
    {
      name: "COVID19 Classifier",
      technologies: ["PyTorch", "Python3", "Ray", "Tensorboard", "SKLearn"],
      year: "2025",
      details: [
        "Self‑taught machine learning concepts from scratch to modern ResNets in PyTorch over 7 days",
        "Developed a custom modular 56‑layer ResNet trained on 33 920 chest X‑ray images to identify COVID‑19, Lung Opacity, and Viral Pneumonia",
        "Integrated Ray Tune and TensorBoard to visualise training metrics and auto‑optimize hyperparameters, filtering outlier runs",
        "Achieved 92.93% classification accuracy on CIFAR‑10, matching top models from the original ResNet paper",
      ],
      link: "https://github.com/kevinh-e/covid19-classifier",
      linkType: "Github",
    },
  ],
  experience: [
    {
      position: "Full‑Stack Developer",
      company: "Google AI in Action Global Event",
      location: "Sydney, NSW",
      period: "May 2025 – Jul 2025",
      details: [
        "Spearheaded a 3‑person design team to launch a B2B SaaS prototype using React, Node.js, and MongoDB",
        "Implemented industry‑standard security with Clerk, Google API integrations, and serverless CI/CD pipelines via GitLab CI → Google Cloud Run & Firebase",
        "Managed end‑to‑end project planning, integration testing, build standardization, and deployment of containerised services on Google Cloud using Docker",
      ],
    },
    {
      position: "Private Tutor",
      company: "",
      location: "",
      period: "Apr 2023 – Present",
      details: [
        "Provided one‑on‑one tutoring in Mathematics and Physics for HSC‑level students",
        "Tailored lessons to suit varying learning styles and behaviours, achieving a 90% success rate in target grades",
        "Created custom practice materials and simplified complex concepts to effectively teach Extension 1 Mathematics",
      ],
    },
  ],
  extracurricular: [
    "Participated in the Titanic – Machine Learning from Disaster Kaggle competition",
    "Participated in DevSoc Hackabyte Hackathon, achieved 2nd place",
    "Built custom PCs; highly experienced in hardware assembly and troubleshooting",
    "Earned an AMEB Certificate of Performance for Piano (Piano Comprehensive Solo Grade 8)",
  ],
  lastUpdated: "June 2025",
};
